### ISSUE TITLE
Switch to using environment variables

### ISSUE THREAD

**Issue by schmmd** [allenai/sbt-plugins#116]
We presently power the deploy plugin with a small file.

https://github.com/allenai/sbt-plugins/blob/master/conf/example_rcfile.conf

I think we should standardize to use the environment variables that @rodneykinney uses.

https://github.com/allenai/s2-offline/blob/master/environments/build-index/aws/README.md

Thoughts?

**Comment by jkinkead** [comment]
This is fairly obsolete. I'm not even sure what this referred to, as both links are dead.

**Comment by schmmd** [comment]
Yeah, I have no idea...
