### ISSUE TITLE
Should set logback.appname

### ISSUE THREAD

**Issue by codeviking** [allenai/sbt-plugins#136]
You can set the `logback.appname` to something sensible via `javaOptions` like so:

``` scala
javaOptions ++= Seq("-Dlogback.appname=parse-banker")
```

Our common plugins should do this so that the log file is sensible named when running via `sbt`.

**Comment by schmmd** [comment]
We can re-use `name` in sbt ;-)

**Comment by jkinkead** [comment]
Sam's template app does:
```scala
javaOptions ++= Seq(s"-Dlogback.appname=${name.value}")
```
This seems like a good default.
