### ISSUE TITLE
Can't resolve flyway depdendency

### ISSUE THREAD

**Issue by codeviking** [allenai/sbt-plugins#155]
With `2015.05.12-1` there's an issue with the flyway dependency:

```
[warn] 	module not found: org.flywaydb#flyway-sbt;3.2.1
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.flywaydb/flyway-sbt/scala_2.10/sbt_0.13/3.2.1/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.flywaydb/flyway-sbt/scala_2.10/sbt_0.13/3.2.1/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/skone/.ivy2/local/org.flywaydb/flyway-sbt/scala_2.10/sbt_0.13/3.2.1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/flywaydb/flyway-sbt_2.10_0.13/3.2.1/flyway-sbt-3.2.1.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.flywaydb#flyway-sbt;3.2.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		org.flywaydb:flyway-sbt:3.2.1 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.flywaydb:flyway-sbt:3.2.1 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 		  +- org.allenai.plugins:allenai-sbt-plugins:2015.05.12-1 (scalaVersion=2.10, sbtVersion=0.13) (/Users/skone/Projects/aristo/project/plugins.sbt#L4-5)
[warn] 		  +- default:aristo-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
```

**Comment by codeviking** [comment]
@markschaake No rush, I updated to `2015.05.08` which has the goodness I'm looking for.

**Comment by markschaake** [comment]
I couldn't repro this. I trashed my `~/.ivy/cache/org.flyway`, set up a brand new SBT project, added the plugins in `project/plugins.sbt`, and SBT was able to start up and re-cache the flyway artifacts. I'll followup in person and see if we can figure out what's up.

**Comment by codeviking** [comment]
Still getting this repeatedly, even after removing `~/.ivy2/cache/org.flywaydb` -- I know @dirkgr just hit this too.

Any other info I can provide that might be helpful?  The error is exactly the same.  Do you have some custom local resolver or something?

**Comment by markschaake** [comment]
Yep, just repro'd it. I forgot that the plugins cache is in a different part of the ivy cache. Steps to repro (in case it doesn't automatically repro):

```
$ rm -rf ~/.ivy2/cache/scala_2.10/sbt_0.13/org.flywaydb
$ sbt
> big stack trace here
```

I'm on it, thanks

**Comment by markschaake** [comment]
I've created a stackoverflow question to address this: http://stackoverflow.com/questions/30248497/is-it-possible-to-add-a-resolver-to-an-sbt-projects-build-via-an-autoplugin

I'll revert remove this plugin in the meantime and publish a new release that isn't broken.

**Comment by arroadie** [comment]
This may be an old error, but just stomped upon it when updating another thing and trying to build my project.
The issue was that flyway changed it's repo from HTTP to HTTPS.
Hope it helps you, future traveler on this thread.
