### ISSUE TITLE
Remove reference to our internal Nexus repository from sbt-plugins.

### ISSUE THREAD

**Issue by schmmd** [allenai/sbt-plugins#229]
Instead, projects should add the Nexus repository directly, as it's deprecated and we would like to start removing it from projects when it's not needed.

https://github.com/allenai/sbt-plugins/blob/master/src/main/scala/org/allenai/plugins/CoreRepositories.scala#L16

Presently, the plugins even inject certain repositories into the resolvers, which is particularly nasty while we're trying to move away!

https://github.com/allenai/sbt-plugins/blob/master/src/main/scala/org/allenai/plugins/CoreRepositories.scala#L32

**Comment by ColinArenz** [comment]
Resolved in change dde7c0ada857cc3d1d761c8835bf93427ed617a2.
