### ISSUE TITLE
Add volume mounts to DockerBuildPlugin

### ISSUE THREAD

**Issue by ColinArenz** [allenai/sbt-plugins#261]
We have a need to map in large shared datastore directories to docker containers both locally and in the cloud. I'd like to add a `dockerVolumes` key that would work something like the following.  Note that we'd also need a way to specify an optional read-only flag.  Docker's default is read-write.

```
// Tuple is in (source, target) or (source, target, option) order. The option can be omitted.
dockerVolumes += ((file("/some/absolute/path"), "/absolute/container/path", "readonly"))
```

Additional possibile features, but not required for my use case:
- Named volume support.
- Custom driver support.

This new `dockerVolumes` key should only affect `dockerRun`, and should not appear as a named volume in the generated Dockerfile, since this would significantly complicate dependency management and cleanup.  Assuming this is only a dockerRun option, the path could be relative (though must be passed to the `docker` CLI as an absolute path).

**Comment by jkinkead** [comment]
I think the `dockerRunFlags` setting handles this well enough.
