### ISSUE TITLE
During dockerBuild, dockerCopyMappings doesn't retain file flags

### ISSUE THREAD

**Issue by ColinArenz** [allenai/sbt-plugins#266]
The ENTRYPOINT directive requires its target to be executable.  If this target is a script copied through `dockerCopyMappings`, the file doesn't retain its +x flag.  Though the build succeeds, this ultimately causes the container to fail to start.

The workaround from Jesse works:
```dockerfile
ENTRYPOINT ["sh", "-c", "chmod +x my_script; exec my_script"]
```

**Comment by jkinkead** [comment]
We use sbt's `IO` class for our copying, and it doesn't attempt to preserve file permissions. If we wish to do this for both files and directories, we'll need to replicate the `copyDirectory` behavior [here](https://github.com/sbt/sbt/blob/c223dccb542beaf763a3a2909cda74bdad39beca/util/io/src/main/scala/sbt/IO.scala#L626-L627), and [`setExecutable()`](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#setExecutable(boolean)) iff the source file is executable.
