### ISSUE TITLE
Log docker command used to execute image

### ISSUE THREAD

**Issue by schmmd** [allenai/sbt-plugins#272]
I would appreciate if [this command were logged](./src/main/resources/org/allenai/plugins/run-docker.sh) so I could easily try alternatives.

**Comment by schmmd** [comment]
Rather [this command](https://github.com/allenai/sbt-plugins/blob/master/src/main/scala/org/allenai/plugins/DockerBuildPlugin.scala#L768).

**Comment by jkinkead** [comment]
Fixed in #275 .

**Comment by schmmd** [comment]
Woohoo @ca16!
