### ISSUE TITLE
First run with private repositories fails

### ISSUE THREAD

**Issue by ColinArenz** [allenai/sbt-plugins#276]
When building a project which uses our default private repository, we've seen an error on several machines.  This only happens on machines with Docker newly installed.

Command (in a DockerBuildPlugin-enabled project):
```
sbt dockerBuild
```

Result:
```
Sending build context to Docker daemon 9.157 MB

Step 1/5 : FROM allenai-docker-private-docker.bintray.io/oracle-java:8

Get https://allenai-docker-private-docker.bintray.io/v2/oracle-java/manifests/8: unauthorized: Unauthorized

...
```

There appears to be a workaround by pulling an image manually, after which everything works:
```
docker pull allenai-docker-private-docker.bintray.io/oracle-java:8
```

**Comment by jkinkead** [comment]
What does "newly installed" mean?

Does running a `docker build` from the commandline with the same dependency cause an error?

**Comment by ColinArenz** [comment]
Newly installed: Having freshly installed Docker, set up credentials, etc.  Essentially following our setup guide for the first time on a machine.

Docker build: We can try this next time we see the issue, but we haven't tried it yet.

**Comment by jkinkead** [comment]
Does the problem resolve itself on reboot?

**Comment by jkinkead** [comment]
Also, did this occur for anyone other than @splittingfield ? He was using the beta client and might have hit a bug.

We've had several people set up Docker since he did without running into issues.

**Comment by ColinArenz** [comment]
We haven't tried a reboot of the machine.  Restarting Docker doesn't resolve the issue.

These people have hit the issue so far: @splittingfield, @cindy21td, @jayantk
