### ISSUE TITLE
Docker file not automatically generated after edits to Dockerfile

### ISSUE THREAD

**Issue by sbhaktha** [allenai/sbt-plugins#284]
It would be helpful is the `Dockerfile` got auto-regenerated every time an edit is made to it.

**Comment by jkinkead** [comment]
I don't understand what this is requesting. Do you mean to have it regenerated if an sbt setting changes that affects it?

**Comment by sbhaktha** [comment]
opened this on @ColinArenz 's suggestion while he was at my desk :)  He just said he addressed it in our TeamCity setup and asked me to close it!
