### ISSUE TITLE
sbt-format doesn't format test sources

### ISSUE THREAD

**Issue by smishmash** [allenai/sbt-plugins#57]
I'm working with the solvers repository, with the proto-inference branch. On sbt when I run `test`, I get warnings about misformatted code:

```
[warn] misformatted: AnalysisBuilderTest.scala
[warn] misformatted: InferenceEngineSpec.scala
[warn] misformatted: KnowledgeBaseSpec.scala
[warn] misformatted: LogicEntitySpec.scala
```

The `format` command however doesn't format these files.

Also, I'd like to know how to format and check the `it` scala files.

**Comment by markschaake** [comment]
`format` now formats test, it, and compile sources
